/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CategoryServiceService } from "../categoryService.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CategoryServiceCreateInput } from "./CategoryServiceCreateInput";
import { CategoryService } from "./CategoryService";
import { CategoryServiceFindManyArgs } from "./CategoryServiceFindManyArgs";
import { CategoryServiceWhereUniqueInput } from "./CategoryServiceWhereUniqueInput";
import { CategoryServiceUpdateInput } from "./CategoryServiceUpdateInput";
import { ServiceFindManyArgs } from "../../service/base/ServiceFindManyArgs";
import { Service } from "../../service/base/Service";
import { ServiceWhereUniqueInput } from "../../service/base/ServiceWhereUniqueInput";
import { ServiceWhereInput } from "../../service/base/ServiceWhereInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CategoryServiceControllerBase {
  constructor(
    protected readonly service: CategoryServiceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CategoryService })
  @nestAccessControl.UseRoles({
    resource: "CategoryService",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createCategoryService(
    @common.Body() data: CategoryServiceCreateInput
  ): Promise<CategoryService> {
    return await this.service.createCategoryService({
      data: {
        ...data,

        service: data.service
          ? {
              connect: data.service,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        slug: true,
        description: true,

        service: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CategoryService] })
  @ApiNestedQuery(CategoryServiceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CategoryService",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async categoryServices(
    @common.Req() request: Request
  ): Promise<CategoryService[]> {
    const args = plainToClass(CategoryServiceFindManyArgs, request.query);
    return this.service.categoryServices({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        slug: true,
        description: true,

        service: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CategoryService })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CategoryService",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async categoryService(
    @common.Param() params: CategoryServiceWhereUniqueInput
  ): Promise<CategoryService | null> {
    const result = await this.service.categoryService({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        slug: true,
        description: true,

        service: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CategoryService })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CategoryService",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateCategoryService(
    @common.Param() params: CategoryServiceWhereUniqueInput,
    @common.Body() data: CategoryServiceUpdateInput
  ): Promise<CategoryService | null> {
    try {
      return await this.service.updateCategoryService({
        where: params,
        data: {
          ...data,

          service: data.service
            ? {
                connect: data.service,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          slug: true,
          description: true,

          service: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CategoryService })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CategoryService",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCategoryService(
    @common.Param() params: CategoryServiceWhereUniqueInput
  ): Promise<CategoryService | null> {
    try {
      return await this.service.deleteCategoryService({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          slug: true,
          description: true,

          service: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/services")
  @ApiNestedQuery(ServiceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Service",
    action: "read",
    possession: "any",
  })
  async findServices(
    @common.Req() request: Request,
    @common.Param() params: CategoryServiceWhereUniqueInput
  ): Promise<Service[]> {
    const query = plainToClass(ServiceFindManyArgs, request.query);
    const results = await this.service.findServices(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        images: true,
        content: true,
        title: true,
        slug: true,

        categoryService: {
          select: {
            id: true,
          },
        },

        price: true,
        discountPrice: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/services")
  @nestAccessControl.UseRoles({
    resource: "CategoryService",
    action: "update",
    possession: "any",
  })
  async connectServices(
    @common.Param() params: CategoryServiceWhereUniqueInput,
    @common.Body() body: ServiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      services: {
        connect: body,
      },
    };
    await this.service.updateCategoryService({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/services")
  @nestAccessControl.UseRoles({
    resource: "CategoryService",
    action: "update",
    possession: "any",
  })
  async updateServices(
    @common.Param() params: CategoryServiceWhereUniqueInput,
    @common.Body() body: ServiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      services: {
        set: body,
      },
    };
    await this.service.updateCategoryService({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/services")
  @nestAccessControl.UseRoles({
    resource: "CategoryService",
    action: "update",
    possession: "any",
  })
  async disconnectServices(
    @common.Param() params: CategoryServiceWhereUniqueInput,
    @common.Body() body: ServiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      services: {
        disconnect: body,
      },
    };
    await this.service.updateCategoryService({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/category-services")
  @swagger.ApiOkResponse({
    type: ServiceWhereInput,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetCategoryServices(
    @common.Body()
    body: string
  ): Promise<ServiceWhereInput[]> {
    return this.service.GetCategoryServices(body);
  }
}
