/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Service as PrismaService,
  CategoryService as PrismaCategoryService,
} from "@prisma/client";
import { ServiceListRelationFilter } from "./ServiceListRelationFilter";

export class ServiceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ServiceCountArgs, "select">): Promise<number> {
    return this.prisma.service.count(args);
  }

  async services(args: Prisma.ServiceFindManyArgs): Promise<PrismaService[]> {
    return this.prisma.service.findMany(args);
  }
  async service(
    args: Prisma.ServiceFindUniqueArgs
  ): Promise<PrismaService | null> {
    return this.prisma.service.findUnique(args);
  }
  async createService(args: Prisma.ServiceCreateArgs): Promise<PrismaService> {
    return this.prisma.service.create(args);
  }
  async updateService(args: Prisma.ServiceUpdateArgs): Promise<PrismaService> {
    return this.prisma.service.update(args);
  }
  async deleteService(args: Prisma.ServiceDeleteArgs): Promise<PrismaService> {
    return this.prisma.service.delete(args);
  }

  async findCategoryServices(
    parentId: string,
    args: Prisma.CategoryServiceFindManyArgs
  ): Promise<PrismaCategoryService[]> {
    return this.prisma.service
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .categoryServices(args);
  }

  async getCategoryService(
    parentId: string
  ): Promise<PrismaCategoryService | null> {
    return this.prisma.service
      .findUnique({
        where: { id: parentId },
      })
      .categoryService();
  }
  async GetServiceBySlug(args: string): Promise<ServiceListRelationFilter> {
    throw new Error("Not implemented");
  }
}
